name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: 'mbstring, xml, zip, gd, pdo_mysql'

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"

      - name: Install Joomla Dependencies
        run: |
          composer install

      - name: Deploy to Azure VM
        run: |
          ssh -vvv -o StrictHostKeyChecking=no root@52.149.213.58
           echo "connection made"
          script: |
            # Clone your Joomla repository
            git clone https://github.com/kishore1278/joomla.git /var/www/html/joomla
            
            # Run Joomla deployment script
            cd /var/www/html/joomla
            chmod +x deploy.sh
            ./deploy.sh
