name: Deploy Joomla to Azure VM

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install unzip
      run: sudo apt-get update && sudo apt-get install unzip -y

    - - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --filename=composer --install-dir=/usr/local/bin
        php -r "unlink('composer-setup.php');"
    
    - name: Create a Composer project for Joomla
      run: |
        composer init -n
        composer require joomla/joomla-cms:3.10.4 # Replace with your desired Joomla version
    

    - name: Push to My Git Remote Repository
      run: |
        git config --global user.email "yuvadonadi17@.com"
        git config --global user.name "kishore1278"
        git add .
        git commit -m "Add Joomla files version ${LATEST_VERSION}"
        git push origin master # Replace 'main' with your desired branch name
